server:
  port: 8787
  servlet:
    context-path: /rig

spring:
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:sinan123}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA_NAME:rig}